easy-translation:
  enable: true
  debug: true
  base-package:
    domain:
      - com.superkele
    translator:
      - com.superkele.demo
  json-serialize: true
logging:
  level:
    com.superkele: debug

